dist: xenial

services:
  - postgresql
addons:
  postgresql:
    - POSTGRESQL_VERSION
      - "9.4"
      - "9.6"
before_script:
  - psql -U postgres -c "create user decide password 'decide'"
  - psql -U postgres -c "create database test_decide owner decide"
  - psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
python:
  - "3.6"
  - "3.8"
install:
  - pip install -r requirements.txt
  - pip install codacy-coverage
script:
  - 01_decice/cd decide
  - coverage run --branch --source=. ./manage.py test authentication && census --keepdb 
  - coverage xml
  - python-codacy-coverage -r coverage.xml
